name: Deploy to Cloudflare Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: cf-pages-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: apps/we-dev-client

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Enable corepack and pnpm
        run: |
          corepack enable
          corepack prepare pnpm@8.15.4 --activate

      - name: Install dependencies (skip scripts)
        run: pnpm install --ignore-scripts --frozen-lockfile=false

      - name: Build
        run: pnpm run builds

      - name: Upload to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: we-dev-pages
          directory: apps/we-dev-client/dist
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
